jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: ./.github/actions/local-s3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build with Ant
      run: ant -noinput -buildfile build.xml dist
    - continue-on-error: true
      name: GWT build
      run: ant -noinput -buildfile build.xml gwtc
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest'
      name: install fuse 2
      run: sudo apt install libfuse2
    - continue-on-error: true
      name: Run tests
      run: ant -noinput -buildfile build.xml test
      timeout-minutes: 120
    - continue-on-error: true
      name: Reproducible build
      run: ./reproducible-test.sh
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ant.yml
